Feature/feedback link
velenyx/feedback-app pull request #12
Opened 2023-09-13 14:10 UTC by mykhailo-svg

## Описание
Отображение линков фидбеков на клиенте

## Что это за Пулл Реквест? (отметьте все применимые)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [x] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [x] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-15 06:58 UTC, velenyx requested changes

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.link {
это не БЭМ вот эти макароны убирай

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +type FeedbacksLinkProps = {
имя

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +  skeleton?: boolean;
isLoading

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <Skeleton animation="wave" width="100%" variant="rectangular" />
вот эти чейнинги вечные со скелетоном, просто смерть
переделай

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +          <div className={styles.info}>
дублирование стилей?

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +          <div className={styles.count}>
каунт чего?

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +            <div className={styles.countItem}>
айтем какого-то количества?

2023-09-15 06:58 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +const FeedbackCard: React.FC<FeedbacksLinkProps> = ({
Не вижу чтоб было ограничение по тексту и текст обрезался

2023-09-15 19:45 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.link {
исправил

2023-09-15 19:47 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +type FeedbacksLinkProps = {
исправил

2023-09-15 19:49 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +  skeleton?: boolean;
исправил

2023-09-15 19:49 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +          <div className={styles.info}>
исправил

2023-09-16 13:50 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <Skeleton animation="wave" width="100%" variant="rectangular" />
исправил

2023-09-16 13:58 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +const FeedbackCard: React.FC<FeedbacksLinkProps> = ({
исправлено

2023-09-16 14:01 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +            <div className={styles.countItem}>
исправлено

2023-09-16 14:01 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +          <div className={styles.count}>
исправлено

2023-09-21 19:40 UTC, velenyx requested changes

2023-09-21 19:40 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              {comments} <img src={commentIcon} alt="" />
оберни мб в спаны чтоб повеселее было

2023-09-21 19:40 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.text {
text_overflow:elipsis

2023-09-22 07:27 UTC, mykhailo-svg commented on client/src/components/FeedbackLink/FeedbackLink.tsx
> +  text: string;
Сделано без нее

2023-09-22 14:32 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.text {
исправлено

2023-09-22 15:11 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              {comments} <img src={commentIcon} alt="" />
исправил

2023-09-22 17:12 UTC, velenyx requested changes

2023-09-22 17:12 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +export default FeedbackCard;
никаких эспортов по дефолту, ЗЛО! ЭКСПОРТЫ ПО ДЕФОЛТУ - 👺👺👺👺👹👹👹👹👹👹

2023-09-22 17:12 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +        <div className={styles.text}>{cutPresentText}</div>
либо в параграф сделай или сделай реакт нодой

2023-09-22 17:21 UTC, TheHeiseDev commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +export default FeedbackCard;
100% экспорты по дефолту не нужно делать

2023-09-22 17:24 UTC, velenyx requested changes

2023-09-22 17:24 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +type FeedbackCardProps = {
через interface

2023-09-22 17:24 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +    <Link to={`feedback/${id}`} className={styles.link}>
для семантической вёрстки оберни в тег article

2023-09-22 17:35 UTC, velenyx requested changes

2023-09-22 17:35 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <span>{comments}</span> <img src={commentIcon} alt="" />
альты!

2023-09-22 17:35 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <img src={viewIcon} alt="" />
аальты

2023-09-23 07:47 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +export default FeedbackCard;
исправил

2023-09-23 07:59 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +type FeedbackCardProps = {
исправлено

2023-09-23 07:59 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +        <div className={styles.text}>{cutPresentText}</div>
исправлено

2023-09-23 08:18 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <img src={viewIcon} alt="" />
исправил

2023-09-23 08:18 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +              <span>{comments}</span> <img src={commentIcon} alt="" />
исправлено

2023-09-23 08:18 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +    <Link to={`feedback/${id}`} className={styles.link}>
исправлено

2023-09-23 16:21 UTC, closed without merging