Feature/widget
velenyx/feedback-app pull request #17
Opened 2023-09-17 15:17 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-17 19:03 UTC, velenyx requested changes

2023-09-17 19:03 UTC, velenyx commented on client/src/pages/Home/Home.tsx
> +          <div className={styles.wrapper}>
чёт тут тысяча дивов лишних не кажется?

2023-09-17 19:03 UTC, velenyx commented on client/src/shared/config/categoryItems.ts
> +export const categoryItems: Categories = {
as const добавь

2023-09-17 19:03 UTC, velenyx commented on client/src/components/Widget/Widget.tsx
> +    backgroundPosition: " bottom right",
вот это вот тут зачем? Если они не динамические?

2023-09-17 19:03 UTC, velenyx commented on client/src/app/store/slice/categories/categoriesThunk.tsx
> +    return data;
снаружи не нужно будет получать что-то кроме data? статусы там и тд?

2023-09-18 07:14 UTC, TheHeiseDev commented on client/src/app/store/slice/categories/categoriesTypes.tsx
> +export enum StatusEnum {
Проще, но это перечисление я использую и в других местах. По этому создал один раз и переиспользую в разных местах

2023-09-18 07:21 UTC, TheHeiseDev commented on client/src/components/Categories/Categories.module.scss
> +.categories {
Ну я по такой структуре всегда верстаю. У меня идет:
1. Основной div блока 
2. Контейнер, в котором я указываю различные свойства блока (padding, flex и тд.) 
3. Дальше уже различные вложенности 

Практически на всех курсах по верстке используется данный подход, так научился так и верстаю

2023-09-18 07:23 UTC, TheHeiseDev commented on client/src/pages/Home/Home.tsx
> +          <div className={styles.wrapper}>
Знаю, что это выглядит как будто накидал дивовов, но тамвсе уместно если разобраться можно понять

2023-09-18 07:23 UTC, TheHeiseDev commented on client/src/shared/config/categoryItems.ts
> +export const categoryItems: Categories = {
+

2023-09-18 07:23 UTC, TheHeiseDev commented on client/src/components/Widget/Widget.tsx
> +    backgroundPosition: " bottom right",
Согласен, перенесу в стили

2023-09-18 07:25 UTC, TheHeiseDev commented on client/src/app/store/slice/categories/categoriesThunk.tsx
> +    return data;
не, все остальное у меня в thunk обрабатывается 
мне тут главное сам массив получить а уже сама обработка запроса идет в extraReducers

2023-09-18 17:53 UTC, velenyx approved these changes

2023-09-18 17:53 UTC, merged