Feature/category
velenyx/feedback-app pull request #18
Opened 2023-09-19 09:12 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-20 18:37 UTC, velenyx requested changes

2023-09-20 18:37 UTC, velenyx commented on client/src/services/AuthService.ts
> +            Authorization: `Bearer ${accessToken}`,
Вот это не нужно самому цеплять, вынеси это в интерцептор самого AXIOS

2023-09-20 18:37 UTC, velenyx commented on client/src/services/AuthService.ts
> +        if (error instanceof AxiosError && error.response?.status === 401) {
Так же 401 ошибки обрабатывай в интерцепторе аксиоса

2023-09-20 18:37 UTC, velenyx commented on client/src/services/AuthService.ts
> +  static async refreshAccessToken(
получается тебе вот этот метод тогда не особо нужен будет, так как ты его руками и вызывать то не будешь

2023-09-21 07:36 UTC, TheHeiseDev commented on client/src/services/AuthService.ts
> +            Authorization: `Bearer ${accessToken}`,
+

2023-09-21 07:37 UTC, TheHeiseDev commented on client/src/services/AuthService.ts
> +        if (error instanceof AxiosError && error.response?.status === 401) {
+

2023-09-21 18:43 UTC, velenyx approved these changes

2023-09-21 18:59 UTC, merged