Feature/feedback link
velenyx/feedback-app pull request #19
Opened 2023-09-23 16:22 UTC by mykhailo-svg

## ОписаниеДобавлено оотображения карточки фидбека

## Что это за Пулл Реквест? (отметьте все применимые)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [x] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [x] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-23 16:37 UTC, velenyx requested changes

2023-09-23 16:37 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.link {
бесполезный класс

2023-09-23 16:37 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +      <Link to={`feedback/${id}`} className={styles.link}>
так же тут убрать бесполезный класс

2023-09-23 16:37 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +                <img src={viewIcon} alt="views-icon" />
альты разве так пишутся?

2023-09-23 16:37 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +                <span>{comments}</span> <img src={commentIcon} alt="comments-icon" />
тоже не особо похоже на норм альт

2023-09-23 16:45 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.module.scss
> +.link {
исправлено

2023-09-23 16:46 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +      <Link to={`feedback/${id}`} className={styles.link}>
исправлено

2023-09-23 16:47 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +                <img src={viewIcon} alt="views-icon" />
исправлено

2023-09-23 16:47 UTC, mykhailo-svg commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +                <span>{comments}</span> <img src={commentIcon} alt="comments-icon" />
исправлено

2023-09-25 19:54 UTC, velenyx approved these changes

2023-09-25 19:54 UTC, velenyx commented on client/src/components/FeedbackCard/FeedbackCard.tsx
> +  const cutPresentText = text.substr(0, 300);
Можешь вот такую штуку приделать, но там вроде стили уже есть. Я не помню если четсно.
const cutPresentText = text.length > 300 ? `${text.substr(0, 300)}...` : text;

2023-09-26 18:22 UTC, merged