Feature/feedback delete
velenyx/feedback-app pull request #21
Opened 2023-09-27 03:49 UTC by mykhailo-svg

## Описание
Документация для фидбека и его удаление,фикс yarn dev

## Что это за Пулл Реквест? (отметьте все применимые)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [x] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [x] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-27 05:24 UTC, velenyx requested changes
Не знаю работает ли дока,  но вроде всё красиво. Красавчик

2023-09-27 05:24 UTC, velenyx commented on server/src/services/feedback.service.js
> +    ...(!(user.role === 'admin') && { user: user._id })
вот это надо точно изменить и чёт придумать с этим

2023-09-27 16:48 UTC, velenyx requested changes

2023-09-27 16:48 UTC, velenyx commented on server/src/services/feedback.service.js
> +  await getFeedbackById(feedbackId);
а зачем?

2023-09-27 16:48 UTC, velenyx commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.UNAUTHORIZED, 'You are not creator of this feedback!');
может лучше сначала проверять авторство?

2023-09-29 06:12 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +    ...(!(user.role === 'admin') && { user: user._id })
с

2023-09-29 06:12 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +    ...(!(user.role === 'admin') && { user: user._id })
исправил

2023-09-29 06:12 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +  await getFeedbackById(feedbackId);
исправил

2023-09-29 06:12 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.UNAUTHORIZED, 'You are not creator of this feedback!');
исправил

2023-09-29 06:37 UTC, velenyx requested changes

2023-09-29 06:37 UTC, velenyx commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.NOT_FOUND, 'Feedback does not exist!');
И так лучше не делать, потому как я тоже хотел так делать. Тут крч если оставлять внутри ошибку то она наверх не будет доставаться и придётся getFeedbackById оборачивать в трай кетч чтоб он ошибку наверх доставал.

2023-09-29 06:37 UTC, velenyx commented on server/src/services/feedback.service.js
> +  const isRequesterAuthor = user._id.toString() === feedbackUser?._id.toString();
const isRequesterAuthor = user._id.toString() === feedbackUser?._id?.toString() ?? false;

2023-09-29 06:37 UTC, velenyx commented on server/src/services/feedback.service.js
> +  if (requesterIsNotAdmin && (!feedbackUser || !isRequesterAuthor)) {
Фидбек юзер мне кажется лишняя проверка так как если нету юзера то isRequesterAuthor будет фолс в любом случае потести я хз

2023-09-29 10:30 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.NOT_FOUND, 'Feedback does not exist!');
исправлено

2023-09-29 10:31 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +  if (requesterIsNotAdmin && (!feedbackUser || !isRequesterAuthor)) {
исправлено

2023-09-29 10:31 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +  const isRequesterAuthor = user._id.toString() === feedbackUser?._id.toString();
исправлено

2023-09-29 13:35 UTC, velenyx approved these changes

2023-09-29 13:36 UTC, merged

2023-09-29 14:30 UTC, velenyx commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/velenyx/feedback-app/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: