Feature/verify page
velenyx/feedback-app pull request #22
Opened 2023-09-27 10:17 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-28 17:57 UTC, velenyx requested changes

2023-09-28 17:57 UTC, velenyx commented on client/src/pages/VerifyEmail/VerifyEmail.tsx
> +    const { token } = qs.parse(window.location.search, { ignoreQueryPrefix: true });
разве этого не может реакт роутер?

2023-09-28 17:57 UTC, velenyx commented on client/src/services/AuthService.ts
> +      console.log("Failed verify Email", error);
можешь для норм ошибок тостер прикрутить

2023-09-28 17:57 UTC, velenyx commented on client/src/shared/config/api.ts
> +export const $apiVerify = axios.create({
а зачем ещё один инстанс?

2023-09-28 17:57 UTC, velenyx commented on client/src/pages/VerifyEmail/VerifyEmail.module.scss
> +    box-shadow: 0 16px 24px rgba(0, 0, 0, 0.15);
такое лучше выносить в ксс вариейблы

2023-09-28 17:57 UTC, velenyx commented on client/src/pages/VerifyEmail/VerifyEmail.module.scss
> +    background-color: white;
это тоже

2023-09-29 06:35 UTC, TheHeiseDev commented on client/src/pages/VerifyEmail/VerifyEmail.tsx
> +    const { token } = qs.parse(window.location.search, { ignoreQueryPrefix: true });
да не, не может вроде 
многие же qs юзают, она там весит мало и четко выполняет свои функции

2023-09-29 06:42 UTC, TheHeiseDev commented on client/src/shared/config/api.ts
> +export const $apiVerify = axios.create({
снес

2023-09-29 06:42 UTC, TheHeiseDev commented on client/src/pages/VerifyEmail/VerifyEmail.module.scss
> +    box-shadow: 0 16px 24px rgba(0, 0, 0, 0.15);
+

2023-09-29 06:42 UTC, TheHeiseDev commented on client/src/pages/VerifyEmail/VerifyEmail.module.scss
> +    background-color: white;
+

2023-09-29 07:28 UTC, TheHeiseDev commented on client/src/services/AuthService.ts
> +      console.log("Failed verify Email", error);
прикрутил

2023-09-29 09:03 UTC, velenyx approved these changes

2023-09-29 09:04 UTC, merged

2023-09-29 14:30 UTC, velenyx commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/velenyx/feedback-app/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: