Feature/profile
velenyx/feedback-app pull request #34
Opened 2023-10-01 07:49 UTC by mykhailo-svg

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-10-01 07:50 UTC, velenyx commented
### Hello from PR Helper

Remember to comment with one of the following states:

`#pr-ready` to enable all auto processing and merging.

`#pr-onhold` to prevent merging as you have other commits or discussions to make.



If you do not set the `#pr-ready` comment then the auto-merge capabilities will not be active.

2023-10-01 09:19 UTC, TheHeiseDev commented on client/src/app/store/slice/profile/profileSlice.ts
> +  myFeedbacks: myFeedback[];
myFeedbacks: myFeedback[]  | null 
 исправь

2023-10-01 09:19 UTC, TheHeiseDev commented on client/src/app/store/slice/profile/profileSlice.ts
> +    page: 0,
page: 1

2023-10-01 09:19 UTC, TheHeiseDev commented on client/src/app/store/slice/profile/profileSlice.ts
> +export const selectMyFeedbacks = (state: RootState) => state.profile;
тут можно для удобства сделать 
export const selectPagination = (state: RootState) => state.profile.meta;

и уже в нужном месте доставать свойства мета через деструктцризацию

2023-10-01 09:19 UTC, TheHeiseDev commented on client/src/app/store/slice/profile/profileTypes.ts
> +  feedbacks: myFeedback[];
feedbacks: myFeedback[] | null;

2023-10-01 09:34 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileSlice.ts
> +  myFeedbacks: [],
исправлено

2023-10-01 09:34 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileThunk.ts
> +  "feedbacks/myFeedbacks",
исправлено

2023-10-01 09:35 UTC, mykhailo-svg commented on client/src/components/MyFeedbacks/MyFeedbacks.tsx
> +    event: React.ChangeEvent<unknown>,
исправлено

2023-10-01 09:36 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileTypes.ts
> +export interface myFeedback {
исправлено

2023-10-01 09:39 UTC, mykhailo-svg commented on client/src/components/MyFeedbacks/MyFeedbacks.tsx
> +        {status === StatusEnum.loading && "loading"}
исправлено

2023-10-01 09:39 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileSlice.ts
> +  myFeedbacks: myFeedback[];
исправлено

2023-10-01 09:39 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileSlice.ts
> +    page: 0,
исправлено

2023-10-01 09:40 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileTypes.ts
> +  feedbacks: myFeedback[];
исправлено

2023-10-01 09:50 UTC, mykhailo-svg commented on client/src/components/MyFeedbacks/MyFeedbacks.module.scss
> +    justify-content: center;
исправлено

2023-10-01 11:50 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileSlice.ts
> +export const selectMyFeedbacks = (state: RootState) => state.profile;
исправил

2023-10-01 11:50 UTC, mykhailo-svg commented on client/src/app/store/slice/profile/profileThunk.ts
> +      `${routePath.MY_FEEDBACKS}?page=${page}&limit=5`
исправлено

2023-10-01 13:49 UTC, TheHeiseDev requested changes

2023-10-01 13:49 UTC, TheHeiseDev commented on client/src/app/store/slice/myFeedbacks/myFeedbacksSlice.ts
> +  name: "profile",
название нужно тоже изменить

2023-10-01 13:49 UTC, TheHeiseDev commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export type myFeedacksSliceInitialState = {
переписать на интерфейс - IMyFeedbackInitialState

2023-10-01 13:49 UTC, TheHeiseDev commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export interface GetMyFeedbacksMeta {
export type -  MyFeedbacksMeta

2023-10-01 13:49 UTC, TheHeiseDev commented on client/src/components/MyFeedbacks/MyFeedbacks.tsx
> +        {status === StatusEnum.success &&
 тут скорее всего rejcted ты хотел написать

2023-10-01 14:10 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export interface GetMyFeedbacksMeta {
исправил

2023-10-01 14:11 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export type myFeedacksSliceInitialState = {
исправил

2023-10-01 18:43 UTC, velenyx requested changes

2023-10-01 18:43 UTC, velenyx commented on client/src/components/MyFeedbacks/MyFeedbacks.tsx
> +        {status === StatusEnum.success && myFeedbacks && feedbackItems}
может быть такое что success и нету фидбеков?

2023-10-01 18:43 UTC, velenyx commented on client/src/shared/config/url.ts
вот это вообще вынести наверное в env и рядом с аксиосом положить наверное

2023-10-01 18:43 UTC, velenyx commented on server/src/app.js
всё связанное с беком убрать

2023-10-01 18:43 UTC, velenyx commented on client/src/components/ProfileInfo/ProfileInfo.tsx
> +export const ProfileInfo = () => {
это не сделано или что это? Он весь пустой какой-то

2023-10-01 18:43 UTC, velenyx commented on client/src/app/store/index.ts
> +    myFeedbacks: myFeedbacksSlice,
всё таки подумай над тем что это слайс профиля

2023-10-04 18:24 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export interface MyFeedback {
исправлено

2023-10-04 18:24 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksSlice.ts
> +  name: "profile",
исправлено

2023-10-04 18:25 UTC, mykhailo-svg commented on client/src/app/store/index.ts
> +    myFeedbacks: myFeedbacksSlice,
исправлено

2023-10-04 18:25 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksThunk.ts
> +      `${routePath.MY_FEEDBACKS}?limit=5&page=${page}`
исправлено

2023-10-04 18:49 UTC, mykhailo-svg commented on client/src/shared/config/url.ts
исправлено

2023-10-04 18:51 UTC, mykhailo-svg commented on client/src/app/store/slice/myFeedbacks/myFeedbacksTypes.ts
> +export interface GetMyFeedbacksMeta {
исправлено

2023-10-04 19:24 UTC, closed without merging