Feature/comments
velenyx/feedback-app pull request #36
Opened 2023-10-03 12:23 UTC by mykhailo-svg

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-10-03 12:23 UTC, velenyx commented
### Hello from PR Helper

Remember to comment with one of the following states:

`#pr-ready` to enable all auto processing and merging.

`#pr-onhold` to prevent merging as you have other commits or discussions to make.



If you do not set the `#pr-ready` comment then the auto-merge capabilities will not be active.

2023-10-03 17:08 UTC, velenyx requested changes

2023-10-03 17:08 UTC, velenyx commented on server/src/routes/v1/comments.route.js
> +router.route('/reply/:replyId').post(auth(), commentsController.createReply);
не понятно зачем одно и тоже по идее 2 раза пишется. Вроде можно до 1 строки сократить

2023-10-06 04:55 UTC, mykhailo-svg commented on server/src/routes/v1/comments.route.js
> +router.route('/reply/:replyId').post(auth(), commentsController.createReply);
исправлено

2023-10-06 04:55 UTC, mykhailo-svg commented on server/src/controllers/comments.controller.js
> +  const comments = await commentsService.getComments(req.params.feedbackId);
исправлено

2023-10-06 17:55 UTC, velenyx requested changes

2023-10-06 17:55 UTC, velenyx commented on server/src/services/comments.service.js
> +  const comments = await Comment.find({ targetId });
проверь работает ли вот это

2023-10-07 14:05 UTC, mykhailo-svg commented on server/src/services/comments.service.js
> +  const comments = await Comment.find({ targetId });
работает

2023-10-08 18:40 UTC, velenyx requested changes

2023-10-08 18:40 UTC, velenyx commented on server/src/models/comment.model.js
> +    createdDate: { type: Date, default: Date.now }
в timestamps вроде есть же created_at? Или почему оно может не подойти?

2023-10-08 18:40 UTC, velenyx commented on server/src/models/reply.model.js
> +    createdDate: { type: Date, default: Date.now }
тоже самое

2023-10-08 18:40 UTC, velenyx commented on server/src/services/comments.service.js
> +    .populate(['creator', 'user'])
зачем 2 раза user делать populate а не в 1м?

2023-10-08 18:40 UTC, velenyx commented on server/src/routes/v1/comments.route.js
забыл ещё валидацию входящих значений

2023-10-09 17:22 UTC, mykhailo-svg commented on server/src/models/comment.model.js
> +    createdDate: { type: Date, default: Date.now }
исправлено

2023-10-09 17:23 UTC, mykhailo-svg commented on server/src/models/reply.model.js
> +    createdDate: { type: Date, default: Date.now }
исправлено

2023-10-09 17:34 UTC, mykhailo-svg commented on server/src/routes/v1/comments.route.js
исправлено

2023-10-11 19:28 UTC, velenyx approved these changes

2023-10-11 19:28 UTC, velenyx commented on server/src/models/plugins/toJSON.plugin.js
> -      delete ret.createdAt;
Точно ли нужно было так радикально вырубать эту тему?

2023-10-12 18:23 UTC, merged