Feature/header
velenyx/feedback-app pull request #4
Opened 2023-08-30 17:33 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-08-30 17:37 UTC, TheHeiseDev commented
added header and footer

2023-08-31 08:09 UTC, velenyx requested changes

2023-08-31 08:09 UTC, velenyx commented on client/src/components/Header/Header.tsx
> +              <span className={styles.navWrapper}>
обычно в спан оборачивают что-то маленькое, а не svg+кнопка

2023-08-31 08:14 UTC, velenyx requested changes

2023-08-31 08:14 UTC, velenyx commented on client/src/components/Footer/Footer.module.scss
> +  & .logoContainer {
вот эту штуку можешь как отдельную часть делать чтоб потом не было тысячи вложенностей

2023-08-31 08:14 UTC, velenyx commented on client/src/components/Header/Header.tsx
> +          className={`${styles.headerBurger} ${burgerToggle && styles.active}`}
вот тут поставь лучше библиотеку classnames или clsx чтоб в классах не было вот такого вот

2023-08-31 09:15 UTC, velenyx requested changes

2023-08-31 09:15 UTC, velenyx commented on client/src/components/Footer/Footer.module.scss
> +@import "../../app/styles/libs/variables";
ты вот тут не импортируй твои CSS переменные, их чтоб использовать не нужно импортировать просто пишешь var(--name) и оно работает. Если у тебя VSCode установи расширение чтоб это всё подсвечивалось

2023-08-31 09:15 UTC, velenyx commented on client/src/components/Footer/Footer.module.scss
> +  background-color: white;
вот такие базовые цвета можешь тоже повыносить в ксс переменные

2023-08-31 09:45 UTC, velenyx commented on client/src/components/Header/Header.tsx
> +          className={`${styles.headerBurger} ${burgerToggle && styles.active}`}
asasd

2023-08-31 09:47 UTC, velenyx approved these changes

2023-08-31 09:48 UTC, merged