Get all categories endpoint
velenyx/feedback-app pull request #6
Opened 2023-08-31 10:37 UTC by mykhailo-svg

## Описание
Ендпоинт для получения всех категорий /category

## Что это за Пулл Реквест? (отметьте все применимые)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [x] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [x] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-08-31 11:24 UTC, velenyx requested changes
Не вижу чтоб в фидбеке была связь с категорией и можно так же сделать чтоб в категории была связь с фидбеком многие к одному.

2023-08-31 11:24 UTC, velenyx commented on server/src/models/category.model.js
> +      required: true
зачем здесь name?

2023-08-31 11:24 UTC, velenyx commented on server/src/controllers/category.controller.js
Не вижу экспорта в паблик АПИ

2023-08-31 11:24 UTC, velenyx commented on server/src/services/category.service.js
> +  await Category.create({ name: 'freelance' });
Зачем здесь создание категории?

2023-08-31 11:24 UTC, velenyx commented on server/src/services/category.service.js
Не вижу эскпорта в паблик АПИ

2023-08-31 11:24 UTC, velenyx commented on server/src/services/category.service.js
> +  if (!categories.length) {
Зачем проверка на length?

2023-08-31 11:24 UTC, velenyx commented on server/src/services/category.service.js
> +    throw new ApiError(httpStatus.NOT_FOUND, 'No categories');
Делай более информативные ошибки. Всмысле нету категорий? Если категории не найдены или другой статус код делай

2023-08-31 11:24 UTC, velenyx commented on server/src/models/category.model.js
> +      enum: category,
Можно сделать lowercase и чтоб была уникальной

2023-08-31 11:28 UTC, mykhailo-svg commented on server/src/models/category.model.js
> +      required: true
Название категории

2023-08-31 12:51 UTC, mykhailo-svg commented on server/src/services/category.service.js
> +  if (!categories.length) {
+

2023-08-31 12:51 UTC, mykhailo-svg commented on server/src/services/category.service.js
> +  await Category.create({ name: 'freelance' });
+

2023-08-31 13:14 UTC, mykhailo-svg commented on server/src/services/category.service.js
Сделал

2023-08-31 13:14 UTC, mykhailo-svg commented on server/src/controllers/category.controller.js
Сделал

2023-09-05 17:14 UTC, velenyx commented on server/src/routes/v1/index.js
> +    path: '/category',
/categories

2023-09-05 17:14 UTC, velenyx commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.NOT_FOUND, 'Set the category!');
Неправильный статус код, "НЕ НАЙДЕНО' а по факту неправильные входящие данные

2023-09-05 17:14 UTC, velenyx commented on server/src/services/feedback.service.js
> +  if (!existingCategory) {
неправильный порядок if перенеси нахождение категории под if(!client

2023-09-08 19:20 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +  if (!existingCategory) {
Сделал

2023-09-08 19:21 UTC, mykhailo-svg commented on server/src/controllers/category.controller.js
> +  res.status(httpStatus.CREATED).send(categories);
исправлено

2023-09-08 19:32 UTC, mykhailo-svg commented on server/src/controllers/feedback.controller.js
> +    category: req.body.category
исправил

2023-09-08 19:33 UTC, mykhailo-svg commented on server/src/controllers/feedback.controller.js
> +  res.send(feedbacks);
исправил

2023-09-08 19:34 UTC, mykhailo-svg commented on server/src/models/feedback.model.js
> +      type: mongoose.Schema.ObjectId
исправил

2023-09-08 20:13 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +    throw new ApiError(httpStatus.NOT_FOUND, 'Set the category!');
исправлено

2023-09-08 20:13 UTC, mykhailo-svg commented on server/src/routes/v1/index.js
> +    path: '/category',
исправлено

2023-09-08 20:13 UTC, mykhailo-svg commented on server/src/services/feedback.service.js
> +  if (!existingCategory) {
исправлено

2023-09-09 16:05 UTC, velenyx approved these changes

2023-09-09 18:17 UTC, merged