Feature/category create
velenyx/feedback-app pull request #7
Opened 2023-09-01 06:09 UTC by mykhailo-svg

## Описание
Ендпоинт для создания категории с валидацией /category/create

## Что это за Пулл Реквест? (отметьте все применимые)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [x] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [x] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-01 07:19 UTC, velenyx requested changes

2023-09-01 07:19 UTC, velenyx commented on server/src/controllers/category.controller.js
> +  res.send(category);
Где статус код?

2023-09-01 07:19 UTC, velenyx commented on server/src/controllers/category.controller.js
> +  const category = await categoriesService.createtCategory(newCategory.toLowerCase());
Сделал ошибку в названии createt

2023-09-01 07:19 UTC, velenyx commented on server/src/models/category.model.js
> +const Category = mongoose.model('Categories', categorySchema);
Почему у нас модель Category, а называется в монго Categories?

2023-09-01 07:19 UTC, velenyx commented on server/src/services/category.service.js
> +const createtCategory = async (newCategory) => {
ошибка в названии

2023-09-01 07:19 UTC, velenyx commented on server/src/routes/v1/categories.route.js
> +  .route('/create')
зачем нам дополнительная приписка /create?

2023-09-01 07:22 UTC, mykhailo-svg commented on server/src/routes/v1/categories.route.js
> +  .route('/create')
Для лучшего понимания вообще

2023-09-02 12:39 UTC, velenyx requested changes

2023-09-02 12:39 UTC, velenyx commented on server/src/routes/v1/categories.route.js
> +router.route('/').post(validate(categoryValidation.category), categoriesController.createCategory);
зачем дублировать ещё раз роутер, засунь в верхний пост запрос

2023-09-02 12:39 UTC, velenyx commented on server/src/validations/categories.validation.js
> +const category = {
что за категория? как я пойму к какому запросу вообще эта валидация
чекай примеры других валидаций

2023-09-02 12:39 UTC, velenyx commented on server/src/controllers/category.controller.js
> +  res.status(httpStatus.CREATED).send(categories);
это что за статус для получение категорий?

2023-09-02 12:39 UTC, velenyx commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
Тут нельзя обойтись .min()? вместо кастомной валидация, кастомная валидация в которой всего лишь проверка на минимально 3 буквы слишком громко

2023-09-02 12:42 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
Вообще делалось на будущее что там будет регулярка еще

2023-09-02 12:48 UTC, mykhailo-svg commented on server/src/controllers/category.controller.js
> +  const category = await categoriesService.createtCategory(newCategory.toLowerCase());
Сделал

2023-09-02 12:51 UTC, mykhailo-svg commented on server/src/models/category.model.js
> +const Category = mongoose.model('Categories', categorySchema);
исправил

2023-09-02 12:51 UTC, mykhailo-svg commented on server/src/services/category.service.js
> +const createtCategory = async (newCategory) => {
исправил

2023-09-02 12:52 UTC, mykhailo-svg commented on server/src/routes/v1/categories.route.js
> +  .route('/create')
исправил

2023-09-02 13:00 UTC, mykhailo-svg commented on server/src/controllers/category.controller.js
> +  res.status(httpStatus.CREATED).send(categories);
исправил

2023-09-02 13:02 UTC, mykhailo-svg commented on server/src/routes/v1/categories.route.js
> +router.route('/').post(validate(categoryValidation.category), categoriesController.createCategory);
исправил

2023-09-02 13:05 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +const category = {
исправил

2023-09-02 13:11 UTC, velenyx commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
Какая? На что там будет проверка регуляркой?

2023-09-02 13:12 UTC, velenyx commented on server/src/controllers/category.controller.js
> +  res.status(httpStatus.CREATED).send(categories);
Не вижу там другого состояния вместо "Создано"

2023-09-02 13:14 UTC, velenyx commented on server/src/routes/v1/categories.route.js
> +router.route('/').post(validate(categoryValidation.category), categoriesController.createCategory);
Не вижу

2023-09-02 13:54 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
чтоб числа не указать и тд

2023-09-02 13:55 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
Ну можно кнш parseint ео уже не то будет

2023-09-05 16:57 UTC, mykhailo-svg commented on server/src/routes/v1/categories.route.js
> +router.route('/').post(validate(categoryValidation.category), categoriesController.createCategory);
Сделал

2023-09-05 16:57 UTC, mykhailo-svg commented on server/src/controllers/category.controller.js
> +  res.status(httpStatus.CREATED).send(categories);
Сделал

2023-09-06 11:44 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +    newCategory: Joi.string().required().custom(newCategoryName)
Сделал

2023-09-06 12:10 UTC, velenyx requested changes

2023-09-06 12:10 UTC, velenyx commented on server/src/validations/categories.validation.js
> +const category = {
непонятно за что отвечает

2023-09-06 13:04 UTC, mykhailo-svg commented on server/src/controllers/index.js
> +module.exports.categoriesController = require('./category.controller');
Сделал

2023-09-06 13:05 UTC, mykhailo-svg commented on server/src/services/index.js
> +module.exports.categoriesService = require('./category.service');
сделал

2023-09-06 13:05 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +const category = {
сделал

2023-09-06 13:08 UTC, velenyx requested changes

2023-09-06 13:08 UTC, velenyx commented on server/src/validations/categories.validation.js
> +const newCategory = {
почему не createCategory?

2023-09-07 09:20 UTC, mykhailo-svg commented on server/src/validations/categories.validation.js
> +const newCategory = {
cделал

2023-09-07 13:36 UTC, merged