Feature/registration
velenyx/feedback-app pull request #8
Opened 2023-09-01 14:17 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-01 19:35 UTC, velenyx requested changes

2023-09-01 19:35 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +      if (status === 201) response.data as IRegisterResponse;
as удалить

2023-09-01 19:35 UTC, velenyx commented on client/src/pages/Register/api/index.ts
> +export const instanceResponse: AxiosInstance = axios.create({
не особо понятно что это такое, обычно инстансы делают через доллар, типо $api.get или $client.get Так сразу понятно что это что-то кастомное

2023-09-01 19:35 UTC, velenyx commented on client/src/shared/config/routePath.ts
>  export const routePath = {
у  тебя это маппинг роутов на фронте, но ты делаешь по ним запросы, лучше такое не делать

2023-09-01 19:35 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +    } catch (error: any) {
any убрать

2023-09-01 19:35 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +      if (code === 400) setRegisterError(true);
не вижу как юзер получит адекватную ошибку при невыполнении регистрации

2023-09-05 09:04 UTC, TheHeiseDev commented on client/src/components/FormRegister/FormRegister.tsx
> +      if (status === 201) response.data as IRegisterResponse;
Исправил

2023-09-05 09:18 UTC, TheHeiseDev commented on client/src/shared/config/routePath.ts
>  export const routePath = {
Поясни пожалуйста, ибо я вообще не вижу здесь проблем 
Зачем создавать отдельно объект где будут роуты и отдельно объект для запросов ? 

Пути же все равно одинаковые я использую

2023-09-05 10:15 UTC, TheHeiseDev commented on client/src/pages/Register/api/index.ts
> +export const instanceResponse: AxiosInstance = axios.create({
Исправил

2023-09-05 10:16 UTC, TheHeiseDev commented on client/src/components/FormRegister/FormRegister.tsx
> +    } catch (error: any) {
Исправил на error: unknown

2023-09-05 10:16 UTC, TheHeiseDev commented on client/src/components/FormRegister/FormRegister.tsx
> +      if (code === 400) setRegisterError(true);
Доработал

2023-09-05 17:31 UTC, velenyx reviewed
Вообще отлично по факту, остались только некоторые микро-моменты

2023-09-05 17:31 UTC, velenyx commented on client/src/components/BurgerMenu/BurgerMenu.tsx
> +            <div className={styles.burgerNavAuth}>
Бро вот тут забыл NavItem или так и надо?

2023-09-05 17:31 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +        if (code === 401) setRegisterError({ state: true, message: message });
ты можешь если ошибка от аксиоса брать и просто ставить ошибку, в любом случае пригодится по идее

2023-09-05 17:31 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +        if (code === 401) setRegisterError({ state: true, message: message });
Но тут тоже хз

2023-09-05 17:31 UTC, velenyx commented on client/src/shared/ui/Buttons/AuthButton.tsx
> +interface IAuthButton {
Можешь удалить I по желанию, но Props надо добавить точно

2023-09-05 17:31 UTC, velenyx commented on client/src/pages/Register/types/index.ts
> +  user: {
Типы всё ещё не поправил, укради их просто из свагера

2023-09-05 17:31 UTC, velenyx commented on client/src/components/FormRegister/FormRegister.tsx
> +        formRef.current?.reset();
Нельзя как-то обойтись без рефа?

2023-09-05 17:33 UTC, velenyx commented on client/src/shared/config/routePath.ts
>  export const routePath = {
Сделай тут as const чтоб объект был только читаемый

2023-09-05 17:34 UTC, velenyx approved these changes

2023-09-06 08:20 UTC, TheHeiseDev commented on client/src/components/BurgerMenu/BurgerMenu.tsx
> +            <div className={styles.burgerNavAuth}>
Так этот блок немного отличается

2023-09-06 08:32 UTC, TheHeiseDev commented on client/src/components/FormRegister/FormRegister.tsx
> +        formRef.current?.reset();
Можно, как оказалось

2023-09-06 08:33 UTC, TheHeiseDev commented on client/src/shared/config/routePath.ts
>  export const routePath = {
Исправил

2023-09-06 08:49 UTC, merged