Feature/auth
velenyx/feedback-app pull request #9
Opened 2023-09-10 17:06 UTC by TheHeiseDev

## Описание

## Что это за Пулл Реквест? (отметьте все применимые)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Связанные билеты и документы

## Добавлены тесты?

- [ ] 👍 yes
- [ ] 🙅 нет, потому что они не нужны
- [ ] 🙋 нет, потому что мне нужна помощь

## Инструкции по контролю качества, Записи

## Добавлено в документацию?

- [ ] 📜 README.md
- [ ] 📓 Swagger
- [ ] 🍕 docs folder
- [ ] 🙅 no documentation needed

## [необязательно] Есть ли какие-либо задачи после развертывания, которые нам необходимо выполнить?

2023-09-13 16:03 UTC, velenyx requested changes

2023-09-13 16:03 UTC, velenyx commented on client/src/services/AuthService.ts
> +    if (status === 200) {
я думаю там не обязательно прям 200 отрабатывать, в любом случае мне кажется если запрос успешен то надо

2023-09-13 16:03 UTC, velenyx commented on client/src/shared/hooks/useAuth.ts
> +    email: user?.email,
мне кажется лучше если if !user а не вот эти ?.

2023-09-15 06:36 UTC, TheHeiseDev commented on client/src/app/store/slice/auth/authSlice.ts
> +export const selectUser = (state: RootState) => state.auth.user;
Так привычнее и удобнее работать

2023-09-15 06:37 UTC, TheHeiseDev commented on client/src/shared/hooks/useAuth.ts
> +    email: user?.email,
Там есть нюанс из-за чего реализовано с помощью токена. Изначально на user и было, но были проблема

2023-09-15 06:38 UTC, TheHeiseDev commented on client/src/services/AuthService.ts
> +      const { data } = await axios.get<User>(BASE_URL + routePath.ME, {
Исправлю

2023-09-15 06:39 UTC, TheHeiseDev commented on client/src/app/store/slice/auth/authSlice.ts
> +export default authSlice.reducer;
Это обязательно ?

2023-09-15 07:09 UTC, TheHeiseDev commented on client/src/services/AuthService.ts
> +    if (status === 200) {
Исправлено

2023-09-15 07:11 UTC, TheHeiseDev commented on client/src/app/store/slice/auth/authSlice.ts
> +export const { setUser, removeUser } = authSlice.actions;
Так привычнее и удобнее. Если не критично, то так и оставлю

2023-09-16 06:46 UTC, velenyx approved these changes

2023-09-16 06:50 UTC, merged